#!/usr/bin/env bash

##############################################################################
##
##  check file size of aia zip file
##
##############################################################################

ls -lh instantapps-demo-instant/build/outputs/apk/debug/